### ISSUE TITLE
Grafana TODO

### ISSUE THREAD

**Issue by jplatte** [freifunkks/salt-conf#1]
This is the current list of what we need to do to get our stats working:
- [x] Complete the grafana configuration (anonymous auth)
- [x] Get excalipurr into the VPN so it can gather alfred data
- [x] Install the grafana backend(s) we need
- [x] Integrate alfred data aggregation scripts
- [ ] <strike>Make excalipurr the only alfred master (multi-master setups will cause trouble because of increased traffic and bad recovery from UDP transmission errors according to someone from Freifunk Hannover)</strike>
- [x] Create grafana dashboards
- [x] Import old data from 2015 via yet broken [rrd2wsp.py](https://github.com/graphite-project/whisper#rrd2whisperpy)
